BUILD:=./build

HD_IMG_NAME:="${BUILD}/hd.img"

all: ${BUILD}/boot/boot.o
	$(shell rm -rf $(HD_IMG_NAME))
	bximage -q -hd=16 -func=create -sectsize=512 -imgmode=flat $(HD_IMG_NAME)
	dd if=$(BUILD)/boot/boot.o of=$(HD_IMG_NAME) bs=512 seek=0 count=1 conv=notrunc

${BUILD}/boot/%.o: kernel
	$(shell mkdir -p ${BUILD}/boot)
	nasm $< -o $@

clean:
	$(shell rm -rf ${BUILD})


qemu: all
	qemu-system-x86_64 -hda $(HD_IMG_NAME)