
THE_OS_NAME := boot
THE_OS_ARCH := x86_64

BUILD := ./build
BIN := $(BUILD)/bin

HD_IMG_PATH := $(BIN)/hd.img
VMWARE_PATH := $(BUILD)/vmware
VMDK_PATH := $(VMWARE_PATH)/$(THE_OS_NAME).vmdk
VMX_PATH := $(VMWARE_PATH)/$(THE_OS_NAME).vmx

$(BUILD)/boot/%.o: kernel/boot/%.asm
	@mkdir -p $(@D)
	nasm -f bin $< -o $@

$(HD_IMG_PATH): $(BUILD)/boot/boot.o
	@mkdir -p $(@D)
	@rm -rf $@
	bximage -q -hd=16 -func=create -sectsize=512 -imgmode=flat $@
	dd if=$< of=$@ bs=512 seek=0 count=1 conv=notrunc

$(VMDK_PATH): $(HD_IMG_PATH)
	@mkdir -p $(@D)
	qemu-img convert -O vmdk -o subformat=streamOptimized $< $@

$(VMX_PATH): $(VMDK_PATH)
	@mkdir -p $(@D)
	@echo "Creating VMware configuration..."
	@echo "\
	.encoding = "UTF-8"\n\
	config.version = "8"\n\
	virtualHW.version = "19"\n\
	memsize = "512"\n\
	displayName = "$(THE_OS_NAME)"\n\
	guestOS = "other"\n\
	numvcpus = "1"\n\
	cpuid.coresPerSocket = "1"\n\
	vhv.enable = "TRUE"\n\
	ide0:0.present = "TRUE"\n\
	ide0:0.fileName = "$(abspath $<)"\n\
	ide0:0.deviceType = "disk"\n\
	floppy0.present = "FALSE"\n\
	ethernet0.present = "TRUE"\n\
	ethernet0.connectionType = "nat"\n\
	sound.present = "FALSE"\n\
	usb.present = "FALSE"\n\
	debugStub.listen.guest32 = "TRUE"\n\
	debugStub.port.guest32 = "8832"\n\
	" > $@
	@echo "VMX file generated at $@"

.PHONY: build rebuild clean run_as_qemu run_as_vmware

build: $(HD_IMG_PATH) $(VMX_PATH)

rebuild: clean build

clean:
	@rm -rf $(BUILD)

run_as_qemu: $(HD_IMG_PATH)
	qemu-system-$(THE_OS_ARCH) -hda $<

run_as_vmware: $(VMX_PATH)
	vmware -x $<